### ISSUE TITLE
Meta tags beheerbaar

### ISSUE THREAD

**Issue by joshuadegier** [larabene/community#15]
De meta tags en social-tags zijn toegevoegd, dienen nu nog beheerbaar gemaakt te worden. Aantal zaken die kunnen gebeuren:

- Twitter / Facebook "handle" in configuratie (@LaraBeNe1)
- Bij een bedrijfsprofiel de mogelijkheid hebben om keywords en description van de pagina te beheren
- Wanneer je op een profielpagina zit het bedrijfslogo als social image gebruiken
- .... ?

**Comment by PendoNL** [comment]
@stijnvanouplines misschien kun jij dit verder oppakken aangezien je hiermee begonnen was?

**Comment by stijnvanouplines** [comment]
@PendoNL komt helemaal goed!
